import { describe, it, expect } from 'vitest'
import bcrypt from 'bcrypt'

/**
 * Password hashes survive a `bcrypt` major upgrade (features/0038).
 *
 * **Why this file exists.** `bcrypt@5.1.1` reached `@mapbox/node-pre-gyp@1`,
 * and through it `tar@6`, `minimatch@3` and `brace-expansion@1` — 24 of the 52
 * advisories affecting the production image, including its only *critical*.
 * `bcrypt@6` replaces node-pre-gyp with `node-gyp-build` and clears all of them
 * at once, which makes the upgrade the single highest-leverage change in that
 * feature. It is also a major, and the thing a major can break here is the only
 * thing that must never break: every `User.passwordHash` already in the
 * database was produced by bcrypt 5.
 *
 * If a new bcrypt cannot verify those, the failure is total and silent at
 * deploy time — nobody can log in, and no test that hashes and compares within
 * one version would notice, because it would agree with itself.
 *
 * So the hashes below are **fixtures, not computed**. They were generated by
 * `bcrypt@5.1.1` on 2026-09-03, before the upgrade, and committed. Regenerating
 * them under the new version would delete the entire point of the file: it
 * would once again be one version agreeing with itself.
 *
 * Do not "refresh" these strings. If one of them ever fails, the upgrade is
 * wrong, not the fixture.
 */

/** Produced by bcrypt@5.1.1 with cost 10. Never regenerate — see above. */
const HASHED_BY_BCRYPT_5 = [
  {
    label: 'ascii',
    password: 'correct-horse-battery-staple',
    hash: '$2b$10$HOmQL97QvE42HNDCEgkstOija0XDwywQNqmHyHLfJAxWWtMUixBBW'
  },
  {
    label: 'non-ascii',
    password: 'contraseña-Ñ-日本語-🔐',
    hash: '$2b$10$TI0Z3bpxUd6AdecNL28SGOeD/DD51ykANQjg1FBjvXFWQNpB.c9DW'
  },
  {
    label: '71 bytes, just under bcrypt truncation',
    password: 'x'.repeat(71),
    hash: '$2b$10$n.oFeb0o5LgEGhmnV1aJE.9v2ZVm7AYVDdWwZSwPfU/7SAg9Kpp.S'
  }
] as const

describe('password hashes written by an earlier bcrypt', () => {
  it.each(HASHED_BY_BCRYPT_5)('verifies the $label hash produced by bcrypt@5.1.1', async ({ password, hash }) => {
    await expect(bcrypt.compare(password, hash)).resolves.toBe(true)
  })

  it.each(HASHED_BY_BCRYPT_5)('rejects a wrong password against the $label hash', async ({ hash }) => {
    await expect(bcrypt.compare('not-the-password', hash)).resolves.toBe(false)
  })

  it('still writes the $2b$ format the stored hashes use', async () => {
    // `routes/auth.ts:125` and `routes/organizations.ts:545` both hash at cost
    // 10. A major that changed the prefix or the cost encoding would make new
    // and old rows two populations, which is worth catching here rather than in
    // production.
    const fresh = await bcrypt.hash('correct-horse-battery-staple', 10)
    expect(fresh).toMatch(/^\$2b\$10\$/)
    await expect(bcrypt.compare('correct-horse-battery-staple', fresh)).resolves.toBe(true)
  })
})
