import { describe, it, expect, beforeEach, vi } from 'vitest'
import request from 'supertest'
import type Stripe from 'stripe'
import { app } from '../../src/app.js'
import { prisma } from '../../src/services/db.js'
import { createUser, createForm, createField, createResponse } from './helpers.js'
import { stripeClient } from '../../src/services/stripe.js'
import { PLANS } from '../../src/services/plans.js'
import {
  subscription,
  subscriptionEvent,
  nextEventId,
  TEST_PRICE_PRO,
  TEST_CUSTOMER
} from '../fixtures/stripe-events.js'
import { logger } from '../../src/services/logger.js'

/**
 * Stripe subscriptions, against a real PostgreSQL
 * ([`features/0013`](../../../features/0013-stripe-subscriptions.md)).
 *
 * These are the three properties the spec says are worth having, and not one of
 * them can be expressed with a mocked Prisma client:
 *
 *   1. **Replay changes nothing.** The idempotency record is a primary-key
 *      collision on `stripe_events`. A mock cannot collide.
 *   2. **Out-of-order events do not accumulate.** The handler is state-setting,
 *      and the proof is that applying the same two events in either order
 *      leaves the database equal to whichever was applied last — never to some
 *      third state built up from both.
 *   3. **A downgrade destroys nothing.** Published forms stay published and
 *      response rows stay present. That is a statement about what is still in
 *      the database after the write, which is exactly what a mock cannot say.
 *
 * And one invariant asserted after every sequence: `Organization.planKey` and
 * `Subscription.status` never disagree, because they are written in one
 * transaction by one function.
 *
 * Every event goes in through **`POST /api/billing/webhook` over HTTP with a
 * genuine Stripe signature**, generated by the SDK's own
 * `generateTestHeaderString`. That is deliberate and it is not ceremony: it is
 * the only way to prove trap 1 — that the raw-body mount really is above
 * `express.json()` in `app.ts`. Calling `handleStripeEvent` directly would pass
 * just as happily against a build where every real webhook is rejected.
 */
describe('stripe subscriptions', () => {
  const WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET!

  /** Posts an event the way Stripe does: raw JSON bytes plus a real signature. */
  async function deliver(event: Stripe.Event) {
    const payload = JSON.stringify(event)
    const signature = stripeClient().webhooks.generateTestHeaderString({
      payload,
      secret: WEBHOOK_SECRET
    })

    return request(app)
      .post('/api/billing/webhook')
      .set('stripe-signature', signature)
      .set('Content-Type', 'application/json')
      .send(payload)
  }

  /** The organization row and its billing row, as they stand right now. */
  async function stateOf(organizationId: string) {
    const [organization, sub] = await Promise.all([
      prisma.organization.findUniqueOrThrow({ where: { id: organizationId } }),
      prisma.subscription.findUnique({ where: { organizationId } })
    ])
    return { planKey: organization.planKey, subscription: sub }
  }

  /**
   * The invariant, checked after every sequence in this file.
   *
   * `planKey` is derived from `Subscription.status` by one function in one
   * transaction. If these two ever disagree, there are two answers to "which
   * plan is this?" — which is the failure `planKey` being derived exists to
   * prevent (features/0013, trap 4).
   */
  async function expectPlanAgreesWithSubscription(organizationId: string) {
    const { planKey, subscription: sub } = await stateOf(organizationId)
    const paid = sub ? ['active', 'trialing', 'past_due'].includes(sub.status) : false
    const onProPrice = sub?.priceId === TEST_PRICE_PRO

    expect(planKey).toBe(paid && onProPrice ? 'pro' : 'free')
  }

  let organizationId: string
  let userId: string
  let authHeader: string

  beforeEach(async () => {
    const account = await createUser()
    organizationId = account.organization.id
    userId = account.user.id
    authHeader = account.authHeader
  })

  describe('a signature is the whole authentication', () => {
    it('rejects an unsigned request with 400 and writes nothing', async () => {
      const event = subscriptionEvent(
        'customer.subscription.created',
        subscription({ organizationId })
      )

      const response = await request(app)
        .post('/api/billing/webhook')
        .set('Content-Type', 'application/json')
        .send(JSON.stringify(event))

      expect(response.status).toBe(400)
      expect(await prisma.subscription.count()).toBe(0)
      // Not even the idempotency record: nothing runs before verification, so a
      // forged event cannot burn its own id and block the real one.
      expect(await prisma.stripeEvent.count()).toBe(0)
      expect((await stateOf(organizationId)).planKey).toBe('free')
    })

    it('rejects a body that was altered after signing', async () => {
      const event = subscriptionEvent(
        'customer.subscription.created',
        subscription({ organizationId })
      )
      const signature = stripeClient().webhooks.generateTestHeaderString({
        payload: JSON.stringify(event),
        secret: WEBHOOK_SECRET
      })

      // The signature is real; the bytes are not the bytes it was made over.
      // This is also the exact failure `express.json()` would cause for *every*
      // event, which is why the raw-body mount in `app.ts` must stay where it is.
      const tampered = JSON.stringify(
        subscriptionEvent('customer.subscription.created', subscription({ organizationId }))
      )

      const response = await request(app)
        .post('/api/billing/webhook')
        .set('stripe-signature', signature)
        .set('Content-Type', 'application/json')
        .send(tampered)

      expect(response.status).toBe(400)
      expect(await prisma.subscription.count()).toBe(0)
    })

    it('accepts a genuine signature and puts the organization on Pro', async () => {
      const response = await deliver(
        subscriptionEvent('customer.subscription.created', subscription({ organizationId }))
      )

      expect(response.status).toBe(200)
      expect(response.body).toEqual({ received: true, processed: true })

      const { planKey, subscription: sub } = await stateOf(organizationId)
      expect(planKey).toBe('pro')
      expect(sub?.status).toBe('active')
      expect(sub?.stripeCustomerId).toBe(TEST_CUSTOMER)
      expect(sub?.priceId).toBe(TEST_PRICE_PRO)
      // Read off the subscription **item** — see `subscriptionStateFrom`. A
      // `null` here is the bug where it was read off the subscription instead.
      expect(sub?.currentPeriodEnd).toEqual(new Date(1769904000 * 1000))
      await expectPlanAgreesWithSubscription(organizationId)
    })
  })

  describe('delivery is at-least-once, so replay must change nothing', () => {
    it('ignores an event id it has already processed', async () => {
      const eventId = nextEventId()
      const active = subscriptionEvent(
        'customer.subscription.created',
        subscription({ organizationId }),
        eventId
      )

      expect((await deliver(active)).body).toEqual({ received: true, processed: true })
      const after = await stateOf(organizationId)

      // The same event id, but carrying a *different* state. If the id were not
      // being honoured this would downgrade the organization, so the assertion
      // is about the id and not about the payload happening to match.
      const replay = subscriptionEvent(
        'customer.subscription.updated',
        subscription({ organizationId, status: 'canceled' }),
        eventId
      )

      const response = await deliver(replay)

      expect(response.status).toBe(200)
      expect(response.body).toEqual({ received: true, processed: false })

      const now = await stateOf(organizationId)
      expect(now.planKey).toBe('pro')
      expect(now.subscription?.status).toBe('active')
      expect(now.subscription?.updatedAt).toEqual(after.subscription?.updatedAt)
      expect(await prisma.stripeEvent.count()).toBe(1)
    })
  })

  describe('order is not guaranteed, so handlers must be state-setting', () => {
    it('leaves the state of whichever event was applied last, in either order', async () => {
      // Forwards: bought, then cancelled.
      await deliver(
        subscriptionEvent('customer.subscription.created', subscription({ organizationId }))
      )
      await deliver(
        subscriptionEvent(
          'customer.subscription.updated',
          subscription({ organizationId, status: 'canceled' })
        )
      )
      expect((await stateOf(organizationId)).planKey).toBe('free')
      await expectPlanAgreesWithSubscription(organizationId)

      // Backwards, in a second organization: the cancellation arrives first.
      // An incremental handler ("downgrade the org") would leave this one free.
      // A state-setting one leaves it on whatever the last event said.
      const { organization: second } = await createUser()
      await deliver(
        subscriptionEvent(
          'customer.subscription.updated',
          subscription({
            organizationId: second.id,
            status: 'canceled',
            customer: 'cus_second',
            id: 'sub_second'
          })
        )
      )
      await deliver(
        subscriptionEvent(
          'customer.subscription.created',
          subscription({ organizationId: second.id, customer: 'cus_second', id: 'sub_second' })
        )
      )

      const state = await stateOf(second.id)
      expect(state.planKey).toBe('pro')
      expect(state.subscription?.status).toBe('active')
      await expectPlanAgreesWithSubscription(second.id)
    })

    it('keeps the paid plan while Stripe is still retrying a failed payment', async () => {
      await deliver(
        subscriptionEvent('customer.subscription.created', subscription({ organizationId }))
      )
      await deliver(
        subscriptionEvent(
          'customer.subscription.updated',
          subscription({ organizationId, status: 'past_due' })
        )
      )

      // `past_due` is not a decision to leave — it is a bank having an opinion,
      // and Stripe retries for days. Cutting the customer off here would take
      // their published forms offline over a card that expired.
      expect((await stateOf(organizationId)).planKey).toBe('pro')
      await expectPlanAgreesWithSubscription(organizationId)
    })

    it('keeps the paid plan for a cancellation scheduled at the period end', async () => {
      await deliver(
        subscriptionEvent(
          'customer.subscription.updated',
          subscription({ organizationId, status: 'active', cancelAtPeriodEnd: true })
        )
      )

      const { planKey, subscription: sub } = await stateOf(organizationId)
      expect(planKey).toBe('pro')
      expect(sub?.cancelAtPeriodEnd).toBe(true)
    })
  })

  describe('a downgrade refuses new state and destroys none of the old', () => {
    it('leaves every published form published and every response present', async () => {
      await deliver(
        subscriptionEvent('customer.subscription.created', subscription({ organizationId }))
      )
      expect((await stateOf(organizationId)).planKey).toBe('pro')

      // Two more published forms than the free plan allows, each with a
      // response somebody actually submitted. The count comes from the
      // catalogue (features/0040) so this keeps being "past the limit" whatever
      // the limit is.
      const overTheLimit = PLANS.free.maxPublishedForms! + 2
      for (let i = 0; i < overTheLimit; i++) {
        const form = await createForm(userId, { title: `Form ${i}`, status: 'published' })
        const field = await createField(form.id, { name: `field_${i}` })
        await createResponse(form.id, { [field.id]: `answer ${i}` })
      }

      await deliver(
        subscriptionEvent(
          'customer.subscription.deleted',
          subscription({ organizationId, status: 'canceled' })
        )
      )

      expect((await stateOf(organizationId)).planKey).toBe('free')

      // The whole point. Those URLs are live and were given to respondents; a
      // billing event is not consent to break them, and it is certainly not
      // consent to delete the answers people already sent (CLAUDE.md, rule 5).
      const stillPublished = await prisma.form.count({
        where: { organizationId, status: 'published' }
      })
      expect(stillPublished).toBe(overTheLimit)

      const responses = await prisma.response.count({
        where: { form: { organizationId } }
      })
      expect(responses).toBe(overTheLimit)

      const answers = await prisma.answer.count({
        where: { response: { form: { organizationId } } }
      })
      expect(answers).toBe(overTheLimit)

      // And the limit does bite on *new* state: a fourth form cannot be
      // published. `assertCanPublishForm` was not changed by this feature —
      // this asserts that it did not need to be, which is the other half of
      // "downgrading refuses new state and destroys none of the old".
      const draft = await createForm(userId, { title: 'Fourth', status: 'draft' })

      const refused = await request(app)
        .patch(`/api/forms/${draft.id}/status`)
        .set('Authorization', authHeader)
        .send({ status: 'published' })

      // 402 is a plan limit; 403 would be a permission failure. They are never
      // collapsed (features/0012).
      expect(refused.status).toBe(402)
      expect(
        await prisma.form.findUniqueOrThrow({ where: { id: draft.id } })
      ).toMatchObject({ status: 'draft' })
    })
  })

  describe('an event serialised by a different API version', () => {
    it('is still reconciled, still answers 200, and says so in the log', async () => {
      const logged = vi.spyOn(logger, 'error').mockImplementation(() => {})

      const event = subscriptionEvent(
        'customer.subscription.created',
        subscription({ organizationId })
      ) as Stripe.Event & { api_version: string }

      // What the account actually sends today: newer than the version
      // `services/stripe.ts` pins. Verified live on 2026-08-31.
      event.api_version = '2026-08-26.dahlia'

      const response = await deliver(event)

      // Refusing would make Stripe retry until it disabled the endpoint,
      // turning a cosmetic drift into a total billing outage. So: processed.
      expect(response.status).toBe(200)
      expect(response.body).toEqual({ received: true, processed: true })
      expect((await stateOf(organizationId)).planKey).toBe('pro')

      // And loud, because the failure this guards against is silence.
      const messages = logged.mock.calls.map(call => String(call[0])).join(' ')
      expect(messages).toContain('2026-08-26.dahlia')

      logged.mockRestore()
    })
  })

  describe('events this application cannot act on', () => {
    it('records an unhandled event type and answers 200', async () => {
      const event = {
        id: nextEventId(),
        object: 'event',
        api_version: '2025-08-27.basil',
        created: 1767225600,
        data: { object: { id: 'in_test', object: 'invoice' } },
        livemode: false,
        pending_webhooks: 0,
        request: { id: null, idempotency_key: null },
        type: 'invoice.payment_succeeded'
      } as unknown as Stripe.Event

      const response = await deliver(event)

      expect(response.status).toBe(200)
      expect(response.body).toEqual({ received: true, processed: false })
      // Recorded, not lost: the row is what says the event was seen. A retry of
      // it must not re-enter the handler either.
      expect(await prisma.stripeEvent.count()).toBe(1)
      expect((await stateOf(organizationId)).planKey).toBe('free')
    })

    it('answers 200 to an event naming an organization it does not know', async () => {
      const response = await deliver(
        subscriptionEvent(
          'customer.subscription.updated',
          subscription({
            organizationId: '00000000-0000-0000-0000-000000000000',
            customer: 'cus_stranger',
            id: 'sub_stranger'
          })
        )
      )

      // A 5xx would make Stripe retry forever an event that will never resolve,
      // and Stripe eventually disables an endpoint that keeps failing — taking
      // every *real* customer's subscription updates with it.
      expect(response.status).toBe(200)
      expect(response.body).toEqual({ received: true, processed: false })
      expect(await prisma.subscription.count()).toBe(0)
    })
  })

  describe('the plan a member sees', () => {
    it('reports the subscription on GET /api/organizations/entitlements, with no Stripe id', async () => {
      const { organization, authHeader } = await createUser()

      await deliver(
        subscriptionEvent(
          'customer.subscription.created',
          subscription({
            organizationId: organization.id,
            customer: 'cus_entitlements',
            id: 'sub_entitlements',
            cancelAtPeriodEnd: true
          })
        )
      )

      const response = await request(app)
        .get('/api/organizations/entitlements')
        .set('Authorization', authHeader)

      expect(response.status).toBe(200)
      expect(response.body.plan.key).toBe('pro')
      expect(response.body.plan.maxResponsesPerMonth).toBe(PLANS.pro.maxResponsesPerMonth)
      expect(response.body.subscription).toEqual({
        status: 'active',
        currentPeriodEnd: new Date(1769904000 * 1000).toISOString(),
        cancelAtPeriodEnd: true
      })

      // No Stripe identifier may reach the client. They are credentials for a
      // third-party API and nothing on screen needs them.
      const body = JSON.stringify(response.body)
      expect(body).not.toContain('cus_')
      expect(body).not.toContain('sub_')
      expect(body).not.toContain('price_')
    })

    it('reports no subscription for an organization that only ever opened checkout', async () => {
      const { organization, authHeader } = await createUser()

      // What `rememberCustomer` writes: a Stripe customer, nothing bought.
      await prisma.subscription.create({
        data: { organizationId: organization.id, stripeCustomerId: 'cus_abandoned' }
      })

      const response = await request(app)
        .get('/api/organizations/entitlements')
        .set('Authorization', authHeader)

      expect(response.status).toBe(200)
      expect(response.body.plan.key).toBe('free')
      // Otherwise "Manage billing" appears for someone who never paid.
      expect(response.body.subscription).toBeNull()
    })
  })
})
